server:
  port: 8082

spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bootdemo1?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: liuyao
  #热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  thymeleaf:
      cache: false
      prefix: classpath:/static/
      suffix: .html
      encoding: UTF-8

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yao.boot1.entity


